server:
  port: 8080
  servlet:
    context-path: /
# 配置日志
logging:
  level:
    # 根目录日志级别
    root: info
    com.xmh.springboot_logback.mapper: debug
    com.xmh.springboot_logback.service: debug
  file:
    path: ./
    name: run.log
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shiro?CharacterEncoding=UTF-8
    username: root
    password: 1234
  # 配置redis
  redis:
    database: 0
    host: localhost
    port: 6379
  servlet:
    multipart:
      max-file-size: 102400000
      max-request-size: 102400000
      location: ./
# 配置mybatis
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.xmh.pojo